@baseUrl = http://localhost:3000

# RECADOS
### Busca todos os recados
GET {{baseUrl}}/recados/?limit=10&offset=10

### Busca um recado específico
GET {{baseUrl}}/recados/2a

### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Este é um novo recado",
    "de": "João da Silva",
    "para": "Maria"
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "Este é um recado atualizado",
    "de": "João da Silva",
    "para": "Maria da Silva"
  }


### Deleta um recado
DELETE {{baseUrl}}/recados/2