@baseUrl = http://localhost:3000

# RECADOS
### Busca todos os recados
GET {{baseUrl}}/recados/?limit=10&offset=10

### Busca um recado específico
GET {{baseUrl}}/recados/1

### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Este é um novo recado",
    "de": "João",
    "para": "Maria",
    "lido": false,
    "data": "2025-05-13T23:44:30.380Z"
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "Este é um recado atualizado",
    "de": "João",
    "para": "Maria",
    "lido": false,
    "data": "2025-05-13T23:44:30.380Z"
  }


### Deleta um recado
DELETE {{baseUrl}}/recados/2