@baseUrl = http://localhost:3000

# RECADOS
### Busca todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0

### Busca um recado específico
GET {{baseUrl}}/recados/4

### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

  {
    "texto": "Este é um novo recado de João para Joana",
    "deId": 6,
    "paraId": 7
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/4
Content-Type: application/json

  {
    "texto": "Este é um recado atualizado"
  }

### Deleta um recado
DELETE {{baseUrl}}/recados/4

##############################

# PESSOAS
### Busca todas as pessoas
GET {{baseUrl}}/pessoas/?limit=10&offset=10

### Busca uma pessoa específica
GET {{baseUrl}}/pessoas/6

### Cria uma nova pessoa
POST {{baseUrl}}/pessoas
Content-Type: application/json

  {
    "email": "joana@email.com",
    "password": "123456",
    "nome": "Joana da Silva"
  }

### Atualiza uma pessoa existente
PATCH {{baseUrl}}/pessoas/3
Content-Type: application/json

  {
    "nome": "João da Silva Atualizado"
  }


### Deleta uma pessoa
DELETE {{baseUrl}}/pessoas/3